# Generated by Django 4.1.1 on 2022-10-12 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
                ('employee_ID', models.TextField(default='', unique=True)),
                ('team', models.TextField(default='')),
                ('hourly_Rate', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_Leader', models.TextField(default='')),
                ('work', models.TextField(default='')),
                ('weekly_Work_Hour', models.IntegerField(default=0)),
                ('department', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.employee')),
            ],
        ),
    ]
