# Generated by Django 4.1.1 on 2022-10-10 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='emplyee_regNo',
            new_name='employee_ID',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='employee_email',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='employee_mobile',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='emplyee_name',
        ),
        migrations.AddField(
            model_name='employee',
            name='hourly_Rate',
            field=models.TextField(default='Not Mentioned'),
        ),
        migrations.AddField(
            model_name='employee',
            name='team',
            field=models.TextField(default='Not Mentioned'),
        ),
        migrations.AddField(
            model_name='employee',
            name='team_leader',
            field=models.TextField(default='Not Mentioned'),
        ),
        migrations.AddField(
            model_name='employee',
            name='work',
            field=models.TextField(default='Not Mentioned'),
        ),
    ]
