# Generated by Django 4.1.1 on 2022-10-10 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_emplyee_regno_employee_employee_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='team_leader',
            new_name='team_Leader',
        ),
        migrations.AddField(
            model_name='employee',
            name='weekly_Work_Hour',
            field=models.TextField(default=''),
        ),
    ]
