# Generated by Django 4.1.1 on 2022-10-12 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_employee_team_department_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_ID',
            field=models.IntegerField(default='', unique=True),
        ),
    ]
