# Generated by Django 4.1.1 on 2022-10-12 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_employee_employee_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='team',
            new_name='create_department',
        ),
        migrations.RemoveField(
            model_name='department',
            name='department',
        ),
        migrations.RemoveField(
            model_name='department',
            name='team_Leader',
        ),
        migrations.RemoveField(
            model_name='department',
            name='weekly_Work_Hour',
        ),
        migrations.RemoveField(
            model_name='department',
            name='work',
        ),
        migrations.CreateModel(
            name='Dep_Emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.TextField(default='')),
                ('team_Leader', models.TextField(default='')),
                ('work', models.TextField(default='')),
                ('weekly_Work_Hour', models.IntegerField(default=0)),
                ('department', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.employee')),
            ],
        ),
    ]
