# Generated by Django 4.1.1 on 2022-10-12 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_team_department_create_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dep_emp',
            name='employee',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.employee'),
        ),
        migrations.AlterField(
            model_name='dep_emp',
            name='department',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.department'),
        ),
    ]
