# Generated by Django 4.1.1 on 2022-10-12 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_dep_emp_employee_alter_dep_emp_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dep_emp',
            name='team',
        ),
    ]
