# Generated by Django 4.1.1 on 2022-10-11 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_employee_department_employ'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='employ',
            new_name='employee',
        ),
    ]
