# Generated by Django 4.1.1 on 2022-10-11 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_employ_department_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='team',
            new_name='work',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='work',
            new_name='team',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='weekly_Work_Hour',
        ),
        migrations.AddField(
            model_name='department',
            name='weekly_Work_Hour',
            field=models.IntegerField(default=0),
        ),
    ]
